# Generated by Django 5.1.3 on 2024-11-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
