# Generated by Django 5.1.3 on 2024-11-28 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_comment_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_counter',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category'),
        ),
    ]
